### ISSUE TITLE
As a submitter, I can partially complete a proposal topic before saving

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/issue-tracker#125]
Requested by David Carroll - HPL. on the 14th May 2021.  Currently not part of the initial feature. This needs more detailed analysis and stakeholder priority selection, before confirmed changed
If considered a requirement, look to move to post project improvements
(SP Requirement list # 104) 

[Linked to change log ID 2](https://stfc365.sharepoint.com/:x:/r/sites/ISISProject-1102/_layouts/15/Doc.aspx?sourcedoc=%7B0ED023B5-D0EC-42A9-B37F-D3FA0B563CAA%7D&file=Issue%20register.xlsx&action=default&mobileredirect=true)

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

Not requested or required. Original request likely originated from legacy
