### ISSUE TITLE
As a PI I am able to specify  the Co-Is permissions to edit or read only

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/issue-tracker#126]
Requested by Emma Gozzard at CLF stakeholder meeting (14th May 2021). 

No way currently to change permission.

Emma G said this is probably fine for the minimum. Consider if this is needed at all. Review with steering group. 

(SP Requirements list # 103)
[
Linked to change ID 3](https://stfc365.sharepoint.com/:x:/r/sites/ISISProject-1102/_layouts/15/Doc.aspx?sourcedoc=%7B0ED023B5-D0EC-42A9-B37F-D3FA0B563CAA%7D&file=Issue%20register.xlsx&action=default&mobileredirect=true)

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

Not needed
