### ISSUE TITLE
Create a new CLF industrial access route

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/issue-tracker#127]
Requested by Rajeev Pattatril and Cristina Gomez-Hernandez at CLF stakeholder meeting (14th May 2021). 

Cristina reported that she felt this would be useful functionality. Would have all the information in one place.  

Andy feels it would be good to keep that call open all the time (Panda confirmed this is something we need to build for ISIS RAPID)

Needs further discussions with stakeholders. At present I will place in P4 further developments. 
[
Linked to change log ID 4](https://stfc365.sharepoint.com/:x:/r/sites/ISISProject-1102/_layouts/15/Doc.aspx?sourcedoc=%7B0ED023B5-D0EC-42A9-B37F-D3FA0B563CAA%7D&file=Issue%20register.xlsx&action=default&mobileredirect=true)

(SP Requirements List # 102)

**Comment by TickleThePanda** [comment]
I think this can be more broadly summarised as industrial access route.

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

Cristina says not to worry until she contacts us
