### ISSUE TITLE
As a round manager, I can't modify the questionnaire while a round is open

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/issue-tracker#129]
Requested by David Carroll at CLF stakeholder meeting (14th May 2021). 

Needs to be defined through policy and process. Needs further clarification 

(SP Requirements list # 100) 
[
Linked to change ID 6](https://stfc365.sharepoint.com/:x:/r/sites/ISISProject-1102/_layouts/15/Doc.aspx?sourcedoc=%7B0ED023B5-D0EC-42A9-B37F-D3FA0B563CAA%7D&file=Issue%20register.xlsx&action=default&mobileredirect=true)

**Comment by TickleThePanda** [comment]
I'm not sure I agree with us forcing the software forcing this - there might be a good reason to modify a call while it's open.

Maybe there could be warnings to the round manager while a call is open instead.

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

We can do this now.
