### ISSUE TITLE
As a round manager, I would like to revert proposals to a previous version or retrieve deleted proposals

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/issue-tracker#133]
Requested by Emma Gozzard (nice to have) 

Not currently, maybe able to handle this through status (revoked?) Need to look into this in more detail (SP requirement list #96)
[Linked to change log ID 10 ](https://stfc365.sharepoint.com/:x:/r/sites/ISISProject-1102/_layouts/15/Doc.aspx?sourcedoc=%7B0ED023B5-D0EC-42A9-B37F-D3FA0B563CAA%7D&file=Issue%20register.xlsx&action=default&mobileredirect=true)

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

User officers and developers know to be careful with deleting proposals and when to withdraw one instead.
