### ISSUE TITLE
Different roles for round officers / site admins

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/issue-tracker#149]
split from #13 

We may want to split up the userOfficer role into separate roles for site admin and round officer to stop round officers editing things such as the privacy notice or footer.

/overwrite opened 2020-09-04

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

Not an issue as limited people have access to the user officer role and they know to be careful using it. It's mostly Emma G doing things. Way around this in the future is to probably implement facilities rather than add additional roles.
