### ISSUE TITLE
Explore the feasibility of tooling that can filter page count within SharePoint for proposals submitted

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/issue-tracker#159]
Linked to issue #19 from Phase 2 MVP LSF

Due to using PDF files the system is unable to automatically reject proposals that are over the page count as set out in the detail within issue #19. There is also a barrier to rejecting those that don't meet the font size criteria. 

To make the process of auditing page count more efficient for staff, following submission, we should explore tooling that may assist with this issue. 

PLEASE NOTE THIS WILL NEED TO BE REVIEWED IF WE INCLUDE THIS IN THE PROJECT OR PART OF BAU. REVIEW END OF PHASE 2

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

Not an issue as we're getting rid of SharePoint and we have upload page limits.
