### ISSUE TITLE
Submitters will be shown clearly for a question whether the information is confidential or public

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/issue-tracker#16]
Submitters will be shown when information is confidential or public to enable the sharing of titles and abstracts and restricting access to commercially sensitive information.

Impacted users: Submitters, FAP Secretaries, Developers, Proposal round managers, Instrument Scientists

Project requirement: [proposal-28](https://stfc365.sharepoint.com/sites/proposals-and-outcomes-transformation-programme/Lists/Proposal%20user%20stories/DispForm.aspx?ID=28)

**Comment by TickleThePanda** [comment]
Ideally, we should have some way of controlling whether or not questions are "public", "default", or "sensitive". This includes the "Title", "Abstract", and "Experimenters". When a user is filling out the proposal form, they should be able to see if a question is public or sensitive.

**Comment by TickleThePanda** [comment]
It would be good to have an understanding about how the existing site works for the user, with the "Public" linking to our policies:
![image](https://user-images.githubusercontent.com/13658288/105970334-29025b00-6081-11eb-8e6c-5abd2eb93275.png)

It will also be good to understand how the ESS questionnaries work.

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

Closed because we have info at the start of the proposal
