### ISSUE TITLE
Integrate with LSF FAP meeting required info and data collection

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/issue-tracker#168]
Part of https://github.com/UserOfficeProject/stfc-user-office-project/issues/11

The FAPs may need structured data available to them.

The LSF FAP results are currently stored in the LSF SharePoint programme site. It's likely that this is a manual process at the moment. We should avoid changing the post FAP upload process.

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

We're looking at how to handle CLF FAPs without SharePoint (@georgeflecknell) and reqs will be captured elsewhere
