### ISSUE TITLE
Submitters will be asked to update their details if they have submitted or are added to a proposal

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/issue-tracker#17]
Submitters will be asked to update their details if they have submitted or are added to a proposal to reduce the likelihood of user's data from being outdated

Impacted users: Submitters

Project requirement: [proposal-37](https://stfc365.sharepoint.com/sites/proposals-and-outcomes-transformation-programme/Lists/Proposal%20user%20stories/DispForm.aspx?ID=37)

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

We already state users must be searchable, non-issue otherwise
