### ISSUE TITLE
Integrate with HPL FAP letters

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/issue-tracker#174]
Part of #11

The LSF FAP letters may be generated by `CLFFAPMaster` - the legacy MSAccess tool (located `\\isis\shares\ULS\_2021_Published_Applications`).

This tool may require data from various sources:
 - LSF SharePoint site
 - CLF proposal database

Ideally, we shouldn't change the existing MSAccess tool but instead should make sure the data is available for the tool.

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

Handled by new FAP letter tool.
