### ISSUE TITLE
Integrate with HPL FAP booklet generation

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/issue-tracker#175]
Part of https://github.com/UserOfficeProject/stfc-user-office-project/issues/11

The HPL FAP booklets may be generated by `CLFFAPMaster` - the legacy MSAccess tool (located `\\isis\shares\ULS\_2021_Published_Applications`).

This tool may require data from various sources:
 - HPL SharePoint site
 - CLF proposal database

Ideally, we shouldn't change the existing MSAccess tool but instead should make sure the data is available for the tool.

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

It's being added to the new booklet tool. Covered by other issues
