### ISSUE TITLE
Integrate with Artemis FAP letters

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/issue-tracker#178]
Part of https://github.com/UserOfficeProject/stfc-user-office-project/issues/11

The Artemis FAP letters may be generated by `CLFFAPMaster` - the legacy MSAccess tool (located `\\isis\shares\ULS\_2021_Published_Applications`).

This tool may require data from various sources:
 - Artemis SharePoint site
 - CLF proposal database

Ideally, we shouldn't change the existing MSAccess tool but instead should make sure the data is available for the tool.

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

Done via separate tool
