### ISSUE TITLE
Integrate with Artemis FAP booklet generation

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/issue-tracker#179]
Part of https://github.com/UserOfficeProject/stfc-user-office-project/issues/11

The LSF FAP booklets are generated by `CLFFAPMaster` - the legacy MSAccess tool (located `\\isis\shares\ULS\_2021_Published_Applications`).

This tool may require data from various sources:
 - LSF SharePoint site
 - CLF proposal database

Ideally, we shouldn't change the existing MSAccess tool but instead should make sure the data is available for the tool.

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

Not needed as they don't use booklets as such
