### ISSUE TITLE
Proposal submission user survey feedback for both legacy and new proposal submission sites

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/issue-tracker#203]
**LSF**

- [x] Send survey and analyse findings (Legacy system)
- [x] Send survey and analyse findings (New Proposal system)

**HPL**

-  [x] Send survey and analyse findings (Legacy system)
-  [x] Send survey and analyse findings (New Proposal system)

**Artemis**

-  [x] Send survey and analyse findings (Legacy system)
-  [x] Send survey and analyse findings (New Proposal system)

**ISIS direct/Riken/Dutch** (May want to separate these up - Discuss with board)

-  [x] Send survey and analyse findings (Legacy system)
-  [x] Send survey and analyse findings (New Proposal system)

* Board only wants ISIS direct (not rapid) We need to check if CLF would like this sent to commercial submitters

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

We do still need to do this for HPL and Artemis

**Comment by mutambaraf** [comment]
Sprint planning: 09/07/2024 - We don't need to do the legacy system.

**Comment by georgeflecknell** [comment]
Sent feedback questionnaires for HPL and ARTEMIS. Deadline 1st August.
