### ISSUE TITLE
Should we link back to the (dev)users domain?

### ISSUE THREAD

**Issue by ACLay** [UserOfficeProject/issue-tracker#224]
The link on the STFC logo leads back to `/`, the root of the current devproposal domain.

We have the logout link, and one to the user's ManageDetails page, but I feel like we should have a link back to our home page.

**Comment by AspectVI** [comment]
@ACLay 
Sorry to bother but is this issue just discussing the possibility of making a change or do we need to make some sort of change? 

If changes are needed then I will pick up this task.

Also, am I mistaken in thinking this is the homepage?
![image](https://user-images.githubusercontent.com/71700965/140895417-4a84af5c-567e-40f4-9752-9d366ab9ff66.png)
As that is where the STFC logo near the top left takes you?

**Comment by ACLay** [comment]
By homepage I meant (dev)users.facilities.rl.ac.uk/auth/Menu.aspx
And I did mean for this to be a discussion to check whether we want to do this.

**Comment by simonfernandes** [comment]
Backlog pruning notes with Emma and George:

It's fine for us to not link back to the main users page
