### ISSUE TITLE
Round managers will be able to manage multiple similar rounds and routes easily

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/issue-tracker#23]
Round managers will be able to manage multiple similar rounds and routes easily to enable easy management of multiple different calls that have very similar content. For example, ISIS Direct and ISIS Rapid

Impacted users: Proposal round managers

Project requirement: [proposal-69](https://stfc365.sharepoint.com/sites/proposals-and-outcomes-transformation-programme/Lists/Proposal%20user%20stories/DispForm.aspx?ID=69)

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

Emma is fine with things as they are with multiple calls.
