### ISSUE TITLE
As a user I would like to see the publication information a little clearer

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/issue-tracker#251]
The publication information field only goes half way across the screen. Request for it to run wider across the screen. 

To review if this is still needed later in the project as the hover function and potentially a change of searchable via DOI would be advisable? 

Can we just out a text field and add the DOI alongside the title?

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

Probably fine, might be an issue for smaller screens but we can address when analysing accessibility.
