### ISSUE TITLE
Submitters will be able to grant, to experimental team members, permission to submit, edit, and read proposals

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/issue-tracker#28]
Submitters will be able to grant, to experimental team members, permission to submit, edit, and read proposals to allow for collaboration between scientists

Do we need permission levels? Are they used at the moment?

Impacted users: Submitters

Project requirement: [proposal-88](https://stfc365.sharepoint.com/sites/proposals-and-outcomes-transformation-programme/Lists/Proposal%20user%20stories/DispForm.aspx?ID=88)

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

Nobody has knowingly requested this in the new system so fine to leave. Members can submit, edit and read.
