### ISSUE TITLE
Users will be able to copy legacy proposals to create new proposals

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/issue-tracker#29]
Users will be able to copy legacy proposals to create new proposals 

Impacted users: Submitters, FAP Secretaries

Project requirement: [proposal-90](https://stfc365.sharepoint.com/sites/proposals-and-outcomes-transformation-programme/Lists/Proposal%20user%20stories/DispForm.aspx?ID=90)

**Comment by mutambaraf** [comment]
Sprint  planning 20/02/2024 : We can have a report like : https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/890 with more filter options which gives links to proposal pdfs for both legacy and new proposal system.

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

No longer an issue as we're too far down the line.
