### ISSUE TITLE
Multiple instruments on a single proposal for CLF

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/issue-tracker#309]
Not part of original scope for CLF. Review at improvements stage. 
Logging here to keep track

[Linked to change log ID 13](https://stfc365.sharepoint.com/:x:/r/sites/ISISProject-1102/_layouts/15/Doc.aspx?sourcedoc=%7B0ED023B5-D0EC-42A9-B37F-D3FA0B563CAA%7D&file=Issue%20register.xlsx&action=default&mobileredirect=true)

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

Not a requested or needed feature.
