### ISSUE TITLE
As a user officer, I want to be able to pick what fields go into the exported excel sheet to share information quickly during the FAP processes

### ISSUE THREAD

**Issue by vyshnavi1605** [UserOfficeProject/issue-tracker#325]
Sarah Needham has requested the following changes to the exported excel sheet when clicking the button shown:
![image](https://user-images.githubusercontent.com/72739242/151014951-205c4acb-aca1-4980-8d11-b7adea3a3589.png)

> Being able to select fields would be great but I imagine that would be a lot more work.
> If it could include:
> Proposal ID
> Title
> Principal investigator
> organisation
> Facility/Area
> Requested weeks (total duration for new programme)
>  
> And if possible (theses I can get via looking at the PDFs and not as intensive as above):
> access route 
> If it’s a resubmission 
> 

Currently this is what is shown in the excel sheet:
![image](https://user-images.githubusercontent.com/72739242/151015541-e0ea0434-1891-4e78-8663-f75a71ee9b59.png)

**Comment by TickleThePanda** [comment]
I think this needs to fit into the reporting tool instead of here for next round. For this round, I think we need to do it "manually" (a query we write against the database) as part of #321.

**Comment by mr-field** [comment]
This may have been done manually for this round. If not, we'll do it with a query for now and complete the issue later.

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

Can be retrieved from reporting tool instead.
