### ISSUE TITLE
As a developer I would like the local environment to be pre seeded with data when deploying for the first time

### ISSUE THREAD

**Issue by keiranjprice101** [UserOfficeProject/issue-tracker#343]
It would make starting development work easier and faster if our local environments were pre populated with data  (questionaries/calls/routes/proposals etc.)

It was suggested this may be achievable in a way similar way to how the db seeds are used in the e2e tests.

This may be able to feed into #338

**Comment by joshhdawes** [comment]
Needs composing

**Comment by joshhdawes** [comment]
To be discussed with Submissions
