### ISSUE TITLE
Submitters will have a grace period (customised by facility) while they are submitting a proposal after the round has closed, this must be clearly communicated to the user

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/issue-tracker#36]
Submitters will have a grace period (customised by facility) while they are submitting a proposal after the round has closed, this must be clearly communicated to the user to allow users have a chance to submit their proposal without losing their data

E.g. users still editing may receive a warning message saying they have x amount of time to save/submit

Impacted users: Submitters

Project requirement: [proposal-17](https://stfc365.sharepoint.com/sites/proposals-and-outcomes-transformation-programme/Lists/Proposal%20user%20stories/DispForm.aspx?ID=17)

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

This hasn't occurred so isn't needed
