### ISSUE TITLE
Instrument scientists will be able to search for proposals by the PDF content

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/issue-tracker#41]
Instrument scientists will be able to search for proposals by the PDF content to make it easier to identify different proposal requirements

Impacted users: Instrument Scientists

Project requirement: [proposal-84](https://stfc365.sharepoint.com/sites/proposals-and-outcomes-transformation-programme/Lists/Proposal%20user%20stories/DispForm.aspx?ID=84)

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

Not a requested feature and we already have ways of searching for proposals by questions answered, and queries.
