### ISSUE TITLE
Submitters will have their form autosaved during completion

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/issue-tracker#42]
Submitters will have their form autosaved during completion to reduce the likelihood of losing data during submission.

This is similar to #20 but would not require the user to click "Save and next step".  We need to consider the feasbility vs cost of doing this.

Impacted users: Submitters

Project requirement: [proposal-87](https://stfc365.sharepoint.com/sites/proposals-and-outcomes-transformation-programme/Lists/Proposal%20user%20stories/DispForm.aspx?ID=87)

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

Might be nice, but we don't think it's a problem currently.
