### ISSUE TITLE
Standardise Time allocation question across templates

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/issue-tracker#513]
To pick up the amount of time requested on the proposal we should have some standard questions with a nice natural key that we can easily pick up in a proposal. If we don't do this we might end up with lots of having to query lots of different questions which is much more work to extract. 
Currently the information in the question with the natural keys:

- Weeks_Requested - LSF Direct Access and Ongoing Programmes
- Ultra_Programme - LSF New Programme
- Octopus_Programme - LSF New Programme

**Comment by mr-field** [comment]
We should check if this is needed to pull proposals into the Scheduler

**Comment by simonfernandes** [comment]
Backlog pruning notes with Emma and George:

This isn't important and everything seems to be working as is.
