### ISSUE TITLE
It is not obvious that a new topic is added

### ISSUE THREAD

**Issue by keiranjprice101** [UserOfficeProject/issue-tracker#516]
When creating a template it is not immediately obvious that a new topic has been created. This is only when the number of topics exceeds the width of the container . For example I failed to realise a topic had been added (as they exceed the red arrow) and ended up adding multiple. Possibly scrolling to the latest topic would make this more clear.

<img width="907" alt="image" src="https://user-images.githubusercontent.com/44777678/161225588-85ce1077-d9b3-4e0a-9b2e-f961fd6dd2fa.png">

**Comment by simonfernandes** [comment]
Backlog pruning notes with Emma and George:

Not an issue
