### ISSUE TITLE
Capture Xpress requirements for proposal submission

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/issue-tracker#58]
We need to capture the ISIS Xpress requirements for the proposal system.

This does not include the sample management and allocation side of the software.

Note 05/04/2023: Emma Gozzard and James Taylor are keen to be included.

---
/overwrite opened 2020-09-04

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

Now complete
