### ISSUE TITLE
Proposal downloads limited to 200 in the Proposal System

### ISSUE THREAD

**Issue by EdwardHaynes** [UserOfficeProject/issue-tracker#581]
The new proposal system only allows a user officer to download max 200 proposals. 

We need to increase the number (1000, or ideally all) for larger calls like ISIS direct. We also need to ensure that when downloading or exporting, all of the proposals are downloaded and it's not restricted to the proposals shown on the current page.

**Comment by EdwardHaynes** [comment]
Here is an example of the limited selection for the LSF 2022_2 call, of which there are 29 proposals:

![image](https://user-images.githubusercontent.com/20170535/170683754-d290c275-ba7c-44dc-9514-2733efc9334c.png)

**Comment by simonfernandes** [comment]
Probably required for #738

**Comment by simonfernandes** [comment]
Will be easier when https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/843 is done

**Comment by simonfernandes** [comment]
Limit is now 200, but still not enough for larger calls like ISIS Direct

**Comment by simonfernandes** [comment]
Backlog pruning notes with Emma and George:

Hi @deepaksftc, was this changed as part of https://github.com/UserOfficeProject/issue-tracker/issues/738? Is there a new limit or is it unrestricted?

**Comment by deepaksftc** [comment]
> Backlog pruning notes with Emma and George:
> 
> Hi @deepaksftc, was this changed as part of #738? Is there a new limit or is it unrestricted?

No, the limit is not changed as part of https://github.com/UserOfficeProject/issue-tracker/issues/738

**Comment by ellen-wright** [comment]
Closing this as already complete
