### ISSUE TITLE
Move LRUCache from the backend to its own package

### ISSUE THREAD

**Issue by mr-field** [UserOfficeProject/issue-tracker#623]
The [`LRUCache`](https://github.com/UserOfficeProject/user-office-backend/blob/87a365a0c3676a67658c0117159211a1c26bbca6/src/utils/LRUCache.ts) backend class is a generic least-recently-used cache which can be used to cache any value in memory for a short time. It was originally added to the core backend to store data returned by the STFC UserOfficeWebService, but can have many other applications: in any situation where we need to get or generate values using a slow process, caching might be used to speed up performance.

To make the cache easier to reuse across all repos, it should be moved into its own NPM package in the [`user-office-lib`](https://github.com/UserOfficeProject/user-office-lib) repo. Other apps, such as the core backend, can then install it from NPM if they need to cache anything.

**Comment by simonfernandes** [comment]
We're no longer using this after https://github.com/UserOfficeProject/user-office-core/pull/811
