### ISSUE TITLE
Release for Artemis

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/issue-tracker#63]
Issue to release for Artemis. This needs to follow the comms plan for the area.

 - [ ] Create and test workflow for area
 - [ ]  Create and test questionnaire
 - [ ]  Test permissions
 - [ ]  Test integrations

This should include all existing routes for Artemis.

/overwrite opened 2020-09-04

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

Complete
