### ISSUE TITLE
Can emails that fail to send (due to network issues) be retried at a later time?

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/issue-tracker#630]
DI seemed to be having some issues this morning with exchange and some of our bus app systems through up email related errors.

This meant that Emma Gozzard didn't get the email from the proposal she submitted this morning, and the logs indicate that it failed to send.

Emma has asked the question: it possible to retry sending these types of emails at a later time so that submitters don't lose out on their confirmation email?

**Comment by simonfernandes** [comment]
**Notes from team sprint planning 14th Dec 2022:**

This is a common problem across software in the wider group, so we may be able to use a cross group solution. Panda to discuss with other team leaders.

**Comment by simonfernandes** [comment]
Sprint planning notes:

We could keep a log of emails like done in the ERA system, or possibly save a PDF of each email.

**Comment by georgeflecknell** [comment]
Raised in scrum of scrums. To be discussed in future plans and to raise at next Away Day.
