### ISSUE TITLE
As a user officer, I would like to easily create pre-approved proposals, so that we can have a simple process to allocating time for experiments through alternative routes

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/issue-tracker#641]
We currently have 2 issues that follow a similar pattern of pre-approved proposals:
 - #301 
 - #640
 
The exact route that proposals are pre-approved are varied (one from another facility, another from our facility). We should find a general solution to these and other possible pre-approved routes.

**Comment by simonfernandes** [comment]
Backlog pruning notes with Emma and George:

Done via approved experiments app
