### ISSUE TITLE
When updating the status of a single proposal the change status modal can highlight status in the proposal workflow

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/issue-tracker#717]
## Which role does this affect.
User officer
## What needs to change.
When updating the status of a single proposal as a user officer the dropdown modal can show different sections of proposal statuses for those in the workflow and those not.
## What is the events it is needed for or affected by.
None
## Why it needs to change.
To improve the user experience.
## Who requested it and when.
During sprint meeting collaboration on 05/10/2022
## Other helpful details like screenshots or email content from.
![image](https://user-images.githubusercontent.com/71100224/194264751-81ca212a-4f58-42b0-a01b-0ba3e9af8604.png)

**Comment by simonfernandes** [comment]
Backlog pruning notes with Emma and George:

This isn't a problem, it's mainly Emma and George using this and they're fine with it.
