### ISSUE TITLE
As a user officer and instrument scientist, I need to be able to download individual PDFs for multiple proposals at a time

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/issue-tracker#738]
Requires https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/581

It's important for scientists, user officers and FAP secretaries across ISIS and CLF to be able to select multiple proposals, click download, and for it to output a package of individual PDFs.

> From: Gozzard, Emma (STFC,RAL,ISIS) <[emma.gozzard@stfc.ac.uk](mailto:emma.gozzard@stfc.ac.uk)>
> Sent: 28 October 2022 10:41
> To: Facilities Business Systems & Support <[FacilitiesBusinessSystem@stfc.ac.uk](mailto:FacilitiesBusinessSystem@stfc.ac.uk)>
> Cc: King, Philip (STFC,RAL,ISIS) <[philip.king@stfc.ac.uk](mailto:philip.king@stfc.ac.uk)>
> Subject: Re: ISIS Direct proposal pdfs 
> 
> While I appreciate that all of the proposals are available in the new system, there are a number of steps to go through to view any given pdf. This is a big step backwards from what we had previously, which is less than ideal. P&O don’t need to view many proposals continually like myself, the UO, Philip, FAP Secs and instrument scientists need to. As such, I would say that making this process easy, which it was previously, should be a priority please.

**Comment by simonfernandes** [comment]
We're currently limited to selecting 200 proposals and the output is a single joined PDF.

**Comment by Cat-Lucifer** [comment]
![image](https://github.com/UserOfficeProject/issue-tracker/assets/108054517/05f5bfdf-8e5b-4a46-b5ff-d812d9b43772)

**Comment by Cat-Lucifer** [comment]
@deepaksftc This sounds good!  This is fine for all facilities.  Thanks 🙂

**Comment by Cat-Lucifer** [comment]
@deepaksftc I think the `Download as single file` and `Download as multiple files` naming would be best.  Thanks!
