### ISSUE TITLE
Automate upload of PDFs to XFAP

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/issue-tracker#748]
For ISIS Direct round 23/1, we [manually uploaded all proposal PDFs](https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/186) to the XFAP site. Going forward, we should automate this so that it's less work for us.

We might be able to do this by modifying the existing script: https://github.com/isisbusapps/internal-scripts/issues/50

**Comment by TickleThePanda** [comment]
This might be easier after #751

**Comment by simonfernandes** [comment]
**Notes from meeting with Sukh, Simon, Philip and Emma 12th Dec 2022:**

Only affects the workload of P&O, so should be considered from a support/developer perspective.

**Comment by simonfernandes** [comment]
Backlog pruning notes with Emma and George:

We have a script to put PDFs sorted by FAP on the U drive which is fine. Not worth the developer effort to automate further.
