### ISSUE TITLE
As a User at STFC, I want to be able to access my legacy proposal PDFs

### ISSUE THREAD

**Issue by ACLay** [UserOfficeProject/issue-tracker#758]
## Which role does this affect.
User
## What needs to change.
On the STFC proposals home we'd need to allow users to reach the proposal site when a round is closed.
## Why it needs to change.
Some users need access to the PDF for their organisations admin processes once we've approved an experiment.
Attempting to navigate to ISIS direct from our homepage just leads to the deactivated link.
## Who requested it and when.
A user from the Bhabha Atomic Research Centre asked for access to the PDFs for their approved proposals on Nov 21st

**Comment by simonfernandes** [comment]
**Notes from meeting with Sukh, Simon, Philip and Emma 12th Dec 2022:**

We need to either import the legacy PDFs to the new software or keep legacy proposals accessible (with clear messaging).

---

Emma is also happy to keep sending them manually on request, though this will likely increase workload on P&O support too.

**Comment by ACLay** [comment]
Would completing the import of legacy proposal data into the new system so it can generate PDFs with that old data be acceptable for this? I don't think it's practical to copy and store the exact legacy PDF files in the new site.

**Comment by simonfernandes** [comment]
> Would completing the import of legacy proposal data into the new system so it can generate PDFs with that old data be acceptable for this? I don't think it's practical to copy and store the exact legacy PDF files in the new site.

@sukhsingh2525 and I would need to check this, as it might depend whether users need to be able to see their science cases in the PDF too. Otherwise I can't see why that wouldn't be an acceptible solution. So long as users have a way of seeing their old data via PDF one way or another. Going this route would require a new PDF template and updated legacy questionnaire template (if we weren't already planning to import the rest).

**Comment by simonfernandes** [comment]
It is still important to append a user's science case to the proposal PDF, so it looks like regenerating one in the new software using legacy data may not be an option.

Emma will keep sending them manually for now.

---

> From: Gozzard, Emma (STFC,RAL,ISIS) <emma.gozzard@stfc.ac.uk> 
> Sent: 02 February 2023 13:39
> To: Fernandes, Simon (STFC,RAL,ISIS) <simon.fernandes@stfc.ac.uk>
> Cc: King, Philip (STFC,RAL,ISIS) <philip.king@stfc.ac.uk>; Singh, Sukhvinder (STFC,RAL,ISIS) <Sukhvinder.Singh@stfc.ac.uk>
> Subject: RE: Giving users access to legacy proposal PDFs
> 
> Hi Simon,
> 
> I think having the science case attached to proposal pdfs is important.
> 
> I can send pdfs upon request.
> 
> Thanks,
> Emma

**Comment by simonfernandes** [comment]
Sprint planning notes:

We don't get many requests per year so the easiest solution is to keep providing them on request.

**Comment by simonfernandes** [comment]
Sprint planning notes:

Needs to be done. Users will need to access thier PDFs when legacy is closed and they should be integrated in the new software rather than a separate site

**Comment by simonfernandes** [comment]
Sprint planning notes:

An option could be to move PDFs into new SharePoint and include a link in legacy proposals. We could include authorisation in the backend

**Comment by simonfernandes** [comment]
Backlog pruning notes with Emma and George:

There is also a need for User Officers and support to be able to access PDFs without having to go through the proposal system. So something like putting them in new SharePoint would be acceptable, as above.
