### ISSUE TITLE
Artemis users will be able to access legacy proposals

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/issue-tracker#84]
Split from https://github.com/UserOfficeProject/stfc-user-office-project/issues/27

/overwrite opened 2020-09-04

**Comment by TickleThePanda** [comment]
We should size this after #82

**Comment by simonfernandes** [comment]
Notes from backlog pruning with George and Emma:

Still needs importing.

**Comment by simonfernandes** [comment]
Now being done as part of https://github.com/UserOfficeProject/issue-tracker/issues/1057
