### ISSUE TITLE
Modify queries to work with the new database for LSF

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/issue-tracker#96]
Split from #78 

Requires #77 and #82 

This is to move all of the queries that use the proposals database for LSF to the new database.

Issues with this:
 - query performance
 - difficulties with IDs or questions changing
 - significant proposal schema differences
 - handle old proposal and new proposal data (within limits)

/overwrite opened 2020-09-04

**Comment by TickleThePanda** [comment]
Possibly blocked by #123

**Comment by mr-field** [comment]
If the local DB is ready, this can be started now. We'll merge it into dev once DB services get it working.
